services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_USER: ${DB_USRNM}
    ports:
      - "3300:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_USER: ${DB_USRNM}
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: npm run dev
